name: PyConPTY Github Actions Workflow

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: windows-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment:
      name: pypi
      url: https://pypi.org/p/pyconpty
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      # retrieve your distributions here

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
